<a href="https://colab.research.google.com/github/Vivek2816/GITHUB-GITAM-OS-Practice-Repo/blob/main/music_recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving spotify_millsongdata.csv to spotify_millsongdata (1).csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("spotify_millsongdata.csv")

In [4]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [5]:
df.shape

(57650, 4)

In [6]:
df.columns

Index(['artist', 'song', 'link', 'text'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57650 entries, 0 to 57649
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   artist  57650 non-null  object
 1   song    57650 non-null  object
 2   link    57650 non-null  object
 3   text    57650 non-null  object
dtypes: object(4)
memory usage: 1.8+ MB

In [8]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop('link', axis=1)

In [11]:
df.head()

,artist,song,text
0,ABBA,Ahe's My Kind Of Girl,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante","Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,Making somebody happy is a question of give an...

In [12]:
df = df.sample(10000, random_state=42)

In [13]:
df.shape

(10000, 3)

In [14]:
df = df.reset_index(drop=True)

In [15]:
df.head()

,artist,song,text
0,Wishbone Ash,Right Or Wrong,Like to have you 'round \r\nWith all the lies...
1,Aerosmith,This Little Light Of Mine,"This Little Light of Mine (Light of Mine), \r..."
2,Fall Out Boy,"Dance, Dance",She says she's no good with words but I'm wors...
3,Janis Joplin,Easy Rider,"Hey mama, mama, come a look at sister, \r\nSh..."
4,Moody Blues,Peak Hour,I see it all through my window it seems. \r\n...

In [20]:
import nltk
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.corpus import stopwords

In [21]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [22]:
stop_words = set(stopwords.words('english'))

In [23]:
ps = PorterStemmer()

testing purpose

In [24]:
ps.stem("playing")

'play'

In [25]:
import re

In [33]:
def preprocess_text(text):
  text=text.lower()
  text = re.sub(r'[^a-zA-Z\s]', '', text)
  text = nltk.word_tokenize(text)
  text = [ps.stem(word) for word in text if word not in stop_words]
  return " ".join(text)

In [35]:
df['text'] = df['text'].apply(preprocess_text)

In [36]:
tfidf = TfidfVectorizer(max_features=5000)

In [37]:
vectors = tfidf.fit_transform(df['text'])

In [38]:
print(vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 566370 stored elements and shape (10000, 5000)>
  Coords	Values
  (0, 2518)	0.06209928653507245
  (0, 3650)	0.12783264362058688
  (0, 2504)	0.10937359169643322
  (0, 2639)	0.07199161265089175
  (0, 4424)	0.08287040595158238
  (0, 1065)	0.11926571911596125
  (0, 3161)	0.10933997391228761
  (0, 3740)	0.0714774504579741
  (0, 4346)	0.15359256652708997
  (0, 3587)	0.2484760637636327
  (0, 4955)	0.33665246885019706
  (0, 2750)	0.121087199224242
  (0, 1793)	0.13945714074821206
  (0, 597)	0.12014051521635041
  (0, 1756)	0.19707172346036822
  (0, 2465)	0.13251274852851094
  (0, 1860)	0.13675211466228215
  (0, 3023)	0.06769640419340471
  (0, 2655)	0.1253906513965034
  (0, 4913)	0.16241711007732157
  (0, 1272)	0.1194510058868472
  (0, 2396)	0.05617649565421386
  (0, 3406)	0.15372182012727156
  (0, 4793)	0.07324595521056261
  (0, 1836)	0.06618723709760131
  :	:
  (9999, 3351)	0.16777858978973176
  (9999, 557)	0.12798747692430795
  (9999, 3907)	0.09779789224627473
  (9999, 4763)	0.1062191532687671
  (9999, 951)	0.1337384974902342
  (9999, 1321)	0.21913886241733424
  (9999, 186)	0.3694298705012129
  (9999, 3627)	0.14880646256785265
  (9999, 4872)	0.11936946169905258
  (9999, 4331)	0.1326443908210006
  (9999, 2949)	0.10610710023508718
  (9999, 1978)	0.15840713761197803
  (9999, 2047)	0.13850894370913175
  (9999, 1326)	0.16550686919658972
  (9999, 408)	0.14507034041185843
  (9999, 2967)	0.12414815970601459
  (9999, 673)	0.13870305848267084
  (9999, 1643)	0.17375325805311972
  (9999, 2262)	0.14660656682543197
  (9999, 1555)	0.12972421997071673
  (9999, 4657)	0.1769217857514094
  (9999, 2313)	0.16496853431470468
  (9999, 83)	0.177777872832543
  (9999, 87)	0.17866298528272634
  (9999, 1869)	0.18052865855051273

In [39]:
similarity = cosine_similarity(vectors)

In [47]:
def recommend(song):
    song_index = df[df['song'] == song].index[0]
    distances = similarity[song_index]
    song_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )

    for i in song_list[1:6]:
      print(
        "Song :", df.iloc[i[0]].song,
        "| Artist :", df.iloc[i[0]].artist
         )

In [48]:
recommend("Hello")

Song : Hello Hello | Artist : Elton John
Song : Hello, hello | Artist : Lady Gaga
Song : Hello God | Artist : Dolly Parton
Song : It's Gonna Be A Good Day | Artist : Jason Mraz
Song : Lhuna | Artist : Coldplay